fullnameOverride: loki-egressd
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: "filesystem"
  structuredConfig:
    frontend:
      max_outstanding_per_tenant: 6000
    query_scheduler:
      max_outstanding_requests_per_tenant: 6000
  limits_config:
    retention_period: 6h

gateway:
  enabled: false

test:
  enabled: false

monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  alerts:
    enabled: false
  serviceMonitor:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false