fullnameOverride: vector-egressd
role: Aggregator

terminationGracePeriodSeconds: 3

customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: true
    address: 127.0.0.1:8686
    playground: false
  sources:
    internal_metrics:
      type: internal_metrics
    vector:
      address: 0.0.0.0:6000
      type: vector
      version: "2"

  transforms:
    tx_bytes_logs:
      type: remap
      inputs:
        - vector
      source: |-
        del(.tx_packets)
        del(.rx_bytes)
        del(.rx_packets)
        del(.ts)

  sinks:
    prom_exporter:
      type: prometheus_exporter
      inputs: [ internal_metrics ]
      address: 0.0.0.0:9090
#    stdout:
#      type: console
#      inputs:
#        - vector
#      encoding:
#        codec: json
    loki_tx_bytes_logs:
      type: loki
      inputs:
        - tx_bytes_logs
      endpoint: "http://loki-headless.egressd.svc.cluster.local:3100"
      compression: "snappy"
      encoding:
        codec: json
      labels:
        forwarder: vector_tx_bytes
        src_pod: '{{ "{{ src_pod }}" }}'
        src_namespace: '{{ "{{ src_namespace }}" }}'
        src_node: '{{ "{{ src_node }}" }}'
        dst_pod: '{{ "{{ dst_pod }}" }}'
        dst_namespace: '{{ "{{ dst_namespace }}" }}'
        dst_node: '{{ "{{ dst_node }}" }}'
        proto: '{{ "{{ proto }}" }}'
      batch:
        timeout_secs: 3
