fullnameOverride: vector
role: Aggregator

terminationGracePeriodSeconds: 3

customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: true
    address: 127.0.0.1:8686
    playground: false
  sources:
    internal_metrics:
      type: internal_metrics
    vector:
      address: 0.0.0.0:6000
      type: vector
      version: "2"

  sinks:
    prom_exporter:
      type: prometheus_exporter
      inputs: [ internal_metrics ]
      address: 0.0.0.0:9090

#    stdout:
#      type: console
#      inputs:
#        - logs
#      encoding:
#        codec: json

    castai:
      type: http
      inputs:
        - vector
      uri: "https://api.cast.ai/v1/security/egress/<your-cluster-id>"
      compression: gzip
      encoding:
        codec: json
      batch:
        max_bytes: 10485760 # 10MB not compressed size.
        timeout_secs: 120
      request:
        headers:
          X-API-Key: "<your-api-key>"
