fullnameOverride: egressd-grafana
adminPassword: admin
grafana.ini:
  server:
    serve_from_sub_path: false
    root_url: /
  analytics:
    check_for_updates: false
  grafana_net:
    url: https://grafana.net
  log:
    mode: console
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Admin
  users:
    default_theme: light

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://egressd-victoria:8428
        access: proxy

dashboards:
  default:
    egressd:
      json: |
       {
         "annotations": {
           "list": [
             {
               "builtIn": 1,
               "datasource": {
                 "type": "grafana",
                 "uid": "-- Grafana --"
               },
               "enable": true,
               "hide": true,
               "iconColor": "rgba(0, 211, 255, 1)",
               "name": "Annotations & Alerts",
               "target": {
                 "limit": 100,
                 "matchAny": false,
                 "tags": [],
                 "type": "dashboard"
               },
               "type": "dashboard"
             }
           ]
         },
         "editable": true,
         "fiscalYearStartMonth": 0,
         "graphTooltip": 0,
         "links": [],
         "liveNow": false,
         "panels": [
           {
             "datasource": {
               "type": "prometheus",
               "uid": "PBFA97CFB590B2093"
             },
             "fieldConfig": {
               "defaults": {
                 "color": {
                   "mode": "palette-classic"
                 },
                 "custom": {
                   "axisCenteredZero": false,
                   "axisColorMode": "text",
                   "axisLabel": "",
                   "axisPlacement": "auto",
                   "barAlignment": 0,
                   "drawStyle": "line",
                   "fillOpacity": 0,
                   "gradientMode": "none",
                   "hideFrom": {
                     "legend": false,
                     "tooltip": false,
                     "viz": false
                   },
                   "lineInterpolation": "linear",
                   "lineWidth": 1,
                   "pointSize": 5,
                   "scaleDistribution": {
                     "type": "linear"
                   },
                   "showPoints": "auto",
                   "spanNulls": false,
                   "stacking": {
                     "group": "A",
                     "mode": "none"
                   },
                   "thresholdsStyle": {
                     "mode": "off"
                   }
                 },
                 "mappings": [],
                 "thresholds": {
                   "mode": "absolute",
                   "steps": [
                     {
                       "color": "green",
                       "value": null
                     },
                     {
                       "color": "red",
                       "value": 80
                     }
                   ]
                 },
                 "unit": "bytes"
               },
               "overrides": []
             },
             "gridPos": {
               "h": 10,
               "w": 12,
               "x": 0,
               "y": 0
             },
             "id": 2,
             "options": {
               "legend": {
                 "calcs": [],
                 "displayMode": "list",
                 "placement": "bottom",
                 "showLegend": true
               },
               "tooltip": {
                 "mode": "single",
                 "sort": "none"
               }
             },
             "targets": [
               {
                 "datasource": {
                   "type": "prometheus",
                   "uid": "PBFA97CFB590B2093"
                 },
                 "editorMode": "code",
                 "expr": "sum(rate(egressd_transmit_bytes_total{dst_namespace!=\"\"}[1m])) by (src_namespace, dst_namespace)",
                 "legendFormat": "{{src_namespace}} to {{dst_namespace}}",
                 "range": true,
                 "refId": "A"
               }
             ],
             "title": "Egress by namespces",
             "type": "timeseries"
           },
           {
             "datasource": {
               "type": "prometheus",
               "uid": "PBFA97CFB590B2093"
             },
             "fieldConfig": {
               "defaults": {
                 "color": {
                   "mode": "palette-classic"
                 },
                 "custom": {
                   "axisCenteredZero": false,
                   "axisColorMode": "text",
                   "axisLabel": "",
                   "axisPlacement": "auto",
                   "barAlignment": 0,
                   "drawStyle": "line",
                   "fillOpacity": 0,
                   "gradientMode": "none",
                   "hideFrom": {
                     "legend": false,
                     "tooltip": false,
                     "viz": false
                   },
                   "lineInterpolation": "linear",
                   "lineWidth": 1,
                   "pointSize": 5,
                   "scaleDistribution": {
                     "type": "linear"
                   },
                   "showPoints": "auto",
                   "spanNulls": false,
                   "stacking": {
                     "group": "A",
                     "mode": "none"
                   },
                   "thresholdsStyle": {
                     "mode": "off"
                   }
                 },
                 "mappings": [],
                 "thresholds": {
                   "mode": "absolute",
                   "steps": [
                     {
                       "color": "green",
                       "value": null
                     },
                     {
                       "color": "red",
                       "value": 80
                     }
                   ]
                 },
                 "unit": "bytes"
               },
               "overrides": []
             },
             "gridPos": {
               "h": 10,
               "w": 12,
               "x": 12,
               "y": 0
             },
             "id": 4,
             "options": {
               "legend": {
                 "calcs": [],
                 "displayMode": "list",
                 "placement": "bottom",
                 "showLegend": true
               },
               "tooltip": {
                 "mode": "single",
                 "sort": "none"
               }
             },
             "targets": [
               {
                 "datasource": {
                   "type": "prometheus",
                   "uid": "PBFA97CFB590B2093"
                 },
                 "editorMode": "code",
                 "expr": "sum(rate(egressd_transmit_bytes_total{dst_zone!=\"\"}[1m])) by (src_zone, dst_zone)",
                 "legendFormat": "{{src_zone}} to {{dst_zone}}",
                 "range": true,
                 "refId": "A"
               }
             ],
             "title": "Egress by zones",
             "type": "timeseries"
           },
           {
             "datasource": {
               "type": "prometheus",
               "uid": "PBFA97CFB590B2093"
             },
             "fieldConfig": {
               "defaults": {
                 "color": {
                   "mode": "palette-classic"
                 },
                 "custom": {
                   "axisCenteredZero": false,
                   "axisColorMode": "text",
                   "axisLabel": "",
                   "axisPlacement": "auto",
                   "barAlignment": 0,
                   "drawStyle": "line",
                   "fillOpacity": 0,
                   "gradientMode": "none",
                   "hideFrom": {
                     "legend": false,
                     "tooltip": false,
                     "viz": false
                   },
                   "lineInterpolation": "linear",
                   "lineWidth": 1,
                   "pointSize": 5,
                   "scaleDistribution": {
                     "type": "linear"
                   },
                   "showPoints": "auto",
                   "spanNulls": false,
                   "stacking": {
                     "group": "A",
                     "mode": "none"
                   },
                   "thresholdsStyle": {
                     "mode": "off"
                   }
                 },
                 "mappings": [],
                 "thresholds": {
                   "mode": "absolute",
                   "steps": [
                     {
                       "color": "green",
                       "value": null
                     },
                     {
                       "color": "red",
                       "value": 80
                     }
                   ]
                 },
                 "unit": "bytes"
               },
               "overrides": []
             },
             "gridPos": {
               "h": 11,
               "w": 12,
               "x": 0,
               "y": 10
             },
             "id": 3,
             "options": {
               "legend": {
                 "calcs": [],
                 "displayMode": "list",
                 "placement": "bottom",
                 "showLegend": true
               },
               "tooltip": {
                 "mode": "single",
                 "sort": "none"
               }
             },
             "targets": [
               {
                 "datasource": {
                   "type": "prometheus",
                   "uid": "PBFA97CFB590B2093"
                 },
                 "editorMode": "code",
                 "expr": "topk(20, sum(rate(egressd_transmit_bytes_total{dst_pod!=\"\"}[5m])) by (src_pod, dst_pod))",
                 "legendFormat": "{{src_pod}} to {{dst_pod}}",
                 "range": true,
                 "refId": "A"
               }
             ],
             "title": "Egress by pods (top 20)",
             "type": "timeseries"
           },
           {
             "datasource": {
               "type": "prometheus",
               "uid": "PBFA97CFB590B2093"
             },
             "fieldConfig": {
               "defaults": {
                 "color": {
                   "mode": "palette-classic"
                 },
                 "custom": {
                   "axisCenteredZero": false,
                   "axisColorMode": "text",
                   "axisLabel": "",
                   "axisPlacement": "auto",
                   "barAlignment": 0,
                   "drawStyle": "line",
                   "fillOpacity": 0,
                   "gradientMode": "none",
                   "hideFrom": {
                     "legend": false,
                     "tooltip": false,
                     "viz": false
                   },
                   "lineInterpolation": "linear",
                   "lineWidth": 1,
                   "pointSize": 5,
                   "scaleDistribution": {
                     "type": "linear"
                   },
                   "showPoints": "auto",
                   "spanNulls": false,
                   "stacking": {
                     "group": "A",
                     "mode": "none"
                   },
                   "thresholdsStyle": {
                     "mode": "off"
                   }
                 },
                 "mappings": [],
                 "thresholds": {
                   "mode": "absolute",
                   "steps": [
                     {
                       "color": "green",
                       "value": null
                     },
                     {
                       "color": "red",
                       "value": 80
                     }
                   ]
                 },
                 "unit": "bytes"
               },
               "overrides": []
             },
             "gridPos": {
               "h": 11,
               "w": 12,
               "x": 12,
               "y": 10
             },
             "id": 6,
             "options": {
               "legend": {
                 "calcs": [],
                 "displayMode": "list",
                 "placement": "bottom",
                 "showLegend": true
               },
               "tooltip": {
                 "mode": "single",
                 "sort": "none"
               }
             },
             "targets": [
               {
                 "datasource": {
                   "type": "prometheus",
                   "uid": "PBFA97CFB590B2093"
                 },
                 "editorMode": "code",
                 "expr": "topk(20, sum(rate(egressd_transmit_bytes_total{dst_pod!=\"\", cross_zone=\"true\"}[5m])) by (src_pod, dst_pod))",
                 "legendFormat": "{{src_pod}} to {{dst_pod}}",
                 "range": true,
                 "refId": "A"
               }
             ],
             "title": "Egress by pods cross zone (top 20)",
             "type": "timeseries"
           },
           {
             "datasource": {
               "type": "prometheus",
               "uid": "PBFA97CFB590B2093"
             },
             "description": "Traffic sent to public ips",
             "fieldConfig": {
               "defaults": {
                 "color": {
                   "mode": "palette-classic"
                 },
                 "custom": {
                   "axisCenteredZero": false,
                   "axisColorMode": "text",
                   "axisLabel": "",
                   "axisPlacement": "auto",
                   "barAlignment": 0,
                   "drawStyle": "line",
                   "fillOpacity": 0,
                   "gradientMode": "none",
                   "hideFrom": {
                     "legend": false,
                     "tooltip": false,
                     "viz": false
                   },
                   "lineInterpolation": "linear",
                   "lineWidth": 1,
                   "pointSize": 5,
                   "scaleDistribution": {
                     "type": "linear"
                   },
                   "showPoints": "auto",
                   "spanNulls": false,
                   "stacking": {
                     "group": "A",
                     "mode": "none"
                   },
                   "thresholdsStyle": {
                     "mode": "off"
                   }
                 },
                 "mappings": [],
                 "thresholds": {
                   "mode": "absolute",
                   "steps": [
                     {
                       "color": "green",
                       "value": null
                     },
                     {
                       "color": "red",
                       "value": 80
                     }
                   ]
                 },
                 "unit": "bytes"
               },
               "overrides": []
             },
             "gridPos": {
               "h": 10,
               "w": 12,
               "x": 0,
               "y": 21
             },
             "id": 5,
             "options": {
               "legend": {
                 "calcs": [],
                 "displayMode": "list",
                 "placement": "bottom",
                 "showLegend": true
               },
               "tooltip": {
                 "mode": "single",
                 "sort": "none"
               }
             },
             "targets": [
               {
                 "datasource": {
                   "type": "prometheus",
                   "uid": "PBFA97CFB590B2093"
                 },
                 "editorMode": "code",
                 "expr": "topk(20, sum(rate(egressd_transmit_bytes_total{dst_ip_type=\"public\"}[5m])) by (src_pod))",
                 "legendFormat": "{{src_pod}}",
                 "range": true,
                 "refId": "A"
               }
             ],
             "title": "Egress by pods to internet (top 20)",
             "type": "timeseries"
           },
           {
             "datasource": {
               "type": "prometheus",
               "uid": "PBFA97CFB590B2093"
             },
             "description": "",
             "fieldConfig": {
               "defaults": {
                 "color": {
                   "mode": "palette-classic"
                 },
                 "custom": {
                   "axisCenteredZero": false,
                   "axisColorMode": "text",
                   "axisLabel": "",
                   "axisPlacement": "auto",
                   "barAlignment": 0,
                   "drawStyle": "line",
                   "fillOpacity": 0,
                   "gradientMode": "none",
                   "hideFrom": {
                     "legend": false,
                     "tooltip": false,
                     "viz": false
                   },
                   "lineInterpolation": "linear",
                   "lineWidth": 1,
                   "pointSize": 5,
                   "scaleDistribution": {
                     "type": "linear"
                   },
                   "showPoints": "auto",
                   "spanNulls": false,
                   "stacking": {
                     "group": "A",
                     "mode": "none"
                   },
                   "thresholdsStyle": {
                     "mode": "off"
                   }
                 },
                 "mappings": [],
                 "thresholds": {
                   "mode": "absolute",
                   "steps": [
                     {
                       "color": "green",
                       "value": null
                     },
                     {
                       "color": "red",
                       "value": 80
                     }
                   ]
                 },
                 "unit": "bytes"
               },
               "overrides": []
             },
             "gridPos": {
               "h": 10,
               "w": 12,
               "x": 12,
               "y": 21
             },
             "id": 7,
             "options": {
               "legend": {
                 "calcs": [],
                 "displayMode": "list",
                 "placement": "bottom",
                 "showLegend": true
               },
               "tooltip": {
                 "mode": "single",
                 "sort": "none"
               }
             },
             "targets": [
               {
                 "datasource": {
                   "type": "prometheus",
                   "uid": "PBFA97CFB590B2093"
                 },
                 "editorMode": "code",
                 "expr": "sum(rate(egressd_transmit_bytes_total{}[5m])) by (proto)",
                 "legendFormat": "{{src_pod}}",
                 "range": true,
                 "refId": "A"
               }
             ],
             "title": "Egress by protocol",
             "type": "timeseries"
           }
         ],
         "schemaVersion": 37,
         "style": "dark",
         "tags": [],
         "templating": {
           "list": []
         },
         "time": {
           "from": "now-5m",
           "to": "now"
         },
         "timepicker": {},
         "timezone": "",
         "title": "Egressd",
         "uid": "egressd",
         "version": 1,
         "weekStart": ""
       }