{{- if .Values.aggregator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "egressd.aggregator.fullname" . }}
  labels:
    {{- include "egressd.aggregator.labels" . | nindent 4 }}
data:
  vector.yaml: |
    api:
      address: 127.0.0.1:8686
      enabled: true
      playground: false
    data_dir: /vector-data-dir
    sources:
      internal_metrics:
        type: internal_metrics
      vector:
        address: 0.0.0.0:6000
        type: vector
        version: "2"
      egressd_http:
        type: "http_server"
        address: "0.0.0.0:8080"
        encoding: "text"

    transforms:
      egressd_logs:
        type: remap
        inputs:
          - egressd_http
        source: |-
          . = parse_json!(string!(.message))

      reduced_egressd_logs:
        type: reduce
        inputs:
          - egressd_logs
        group_by:
          - src_ip
          - dst_ip
          - proto
        merge_strategies:
          tx_bytes: retain
          tx_packets: retain
          rx_bytes: retain
          rx_packets: retain
          ts: retain
        expire_after_ms: 5000

    sinks:
      prom_exporter:
        type: prometheus_exporter
        inputs: [ internal_metrics ]
        address: 0.0.0.0:9090
    {{- if .Values.castai.clusterID }}
      castai:
        type: http
        inputs:
          - reduced_egressd_logs
        uri: "{{.Values.castai.apiURL}}/v1/security/egress/{{.Values.castai.clusterID}}"
        compression: gzip
        encoding:
          codec: json
        batch:
          max_bytes: {{ .Values.aggregator.castaiSink.maxBytes }}
          timeout_secs: {{ .Values.aggregator.castaiSink.timeoutSecs }}
        request:
          headers:
            X-API-Key: "${CASTAI_API_KEY}"
    {{- end }}

    {{- if .Values.aggregator.logToStdout}}
      stdout:
        type: console
        inputs:
          - reduced_egressd_logs
        encoding:
          codec: json
    {{- end }}
{{- end }}
