name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CHART_PATH: "${{ github.workspace }}/charts/egressd"


jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    if: ${{ github.event.head_commit.message != '[Release] Update Chart.yaml' }}
    steps:
      - name: Ciprian test - 1 - Checkout helm-charts
        # The cr tool only works if the target repository is already checked out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: castai/helm-charts
          path: helm-charts
          token: ${{ secrets.HELM_CHARTS_REPO_TOKEN }}

      - name: Ciprian test - 2 - test chart sync
        run: |
          cd helm-charts
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git checkout main
          echo "chart path: ${CHART_PATH}"
          ls ${CHART_PATH}
          pwd
          echo "finish"

  e2e:
    name: E2E
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'pull_request' }}
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go 1.20
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.7.0
        with:
          config: ./e2e/kind-config.yaml
          version: "v0.20.0"
          cluster_name: e2e

      - name: Run e2e
        shell: bash
        run: |
          KIND_CONTEXT=e2e IMAGE_TAG=${{ github.sha }} ./e2e/run.sh
